### ISSUE TITLE
No Gitter::Client namespace

### ISSUE THREAD

**Issue by jakshi** [kristenmills/ruby-gitter#5]
When I try:

```
require 'gitter'

# Create a new client
client = Gitter::Client.new('MY_SECURE_TOKEN')
```

I get:

```
test.rb:6:in `<main>': uninitialized constant Gitter::Client (NameError)
```

How to use the gem?

**Comment by kristenmills** [comment]
I don't think I ever published a version of this gem that did anything.  I can do that. I'll close this issue when I do.

**Comment by jakshi** [comment]
Hello Kristen,

Sorry for disturbing you. I just found it here: https://rubygems.org/gems/ruby-gitter/versions/0.0.1
So I thought it supposed to work.

I would be glad to see the wrapper/library working, but it's totally up to you.

Anyhow that you for answer.

Kindest Regards.
Konstantin.

**Comment by kristenmills** [comment]
Don't worry about it. Yeah the 0.0.1 version is just me claiming the name of the gem. It doesn't do anything. I'll publish 0.1.0 in the next few days and that will actually have functionality. If you don't want to wait that long, you can include this in your Gemfile

```ruby
gem 'ruby-gitter', git: 'https://github.com/kristemills/ruby-gitter.git'
```
That will pull directly from the github repo.

**Comment by kristenmills** [comment]
Sorry I took so long. Version 0.1.0 is now published and should reflect the Readme

**Comment by jakshi** [comment]
Hello Kristen,

I totally understand that people can have no free time, so thank you a lot for releasing working version.

Kindest Regards.
Konstantin.
